set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_BUILD_TYPE release)

if(PORT STREQUAL "libgit2" OR PORT STREQUAL "libplist" OR PORT STREQUAL "libarchive")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
    set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DCMAKE_POLICY_VERSION_MINIMUM=3.15)
else()
    set(VCPKG_LIBRARY_LINKAGE static)
    set(VCPKG_CMAKE_CONFIGURE_OPTIONS
        -DCMAKE_POLICY_VERSION_MINIMUM=3.15
        -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
    )
    set(VCPKG_C_FLAGS_RELEASE "/O1 /Os /Gy")
    set(VCPKG_CXX_FLAGS_RELEASE "/O1 /Os /Gy")
    set(VCPKG_LINKER_FLAGS_RELEASE "/OPT:REF /OPT:ICF")
endif()